name: Docker Image CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      docker-tagname:
        description: Tag name of the Docker image
        default: 'ocrd/sbb_binarization'

env:
  DOCKER_TAGNAME: ${{ github.evenv.inputs.docker-tagname || 'ocrd/sbb_binarization' }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - # Activate cache export feature to reduce build time of image
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      run: make docker DOCKER_TAG=${{ env.DOCKER_TAGNAME }}
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image to Dockerhub
      run: docker push ${{ env.DOCKER_TAGNAME }}
    - name: Alias the Docker image for GHCR
      run: docker tag ${{ env.DOCKER_TAGNAME }} ghcr.io/${{ github.repository }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image to Github Container Registry
      run: docker push ghcr.io/${{ github.repository }}
